# Travis Configuration
#
# Travis runs the tests configured in tox.ini using tox-travis.  Tox is a
# automation tool for running tests in isolated virtual environments.

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

install: pip install tox-travis

script: tox
